### ISSUE TITLE
API calls in stores?

### ISSUE THREAD

**Issue by kahlil** [rangle/ngcourse-next#25]
You currently put your API calls into the stores. That is considered a Flux anti-pattern.
A more optimal solution would be to move the API calls to a helper class and use them in the Action Creators. The API calls then also trigger actions like "GET_TASKS" and "RECEIVE_TASKS" to which the components can react. 

Further reading: 
* https://medium.com/@tribou/flux-getting-data-from-an-api-b73b6478c015
* http://facebook.github.io/react/blog/2014/07/30/flux-actions-and-the-dispatcher.html

**Comment by igor-ka** [comment]
@kahlil thank you for your feedback.
Yeah you are right, we have discussed this internally, just need to propagate this change into here.

**Comment by kahlil** [comment]
@igor-ka cool :smile:
