### ISSUE TITLE
$scope digest not triggered after Store change

### ISSUE THREAD

**Issue by steven-ks** [rangle/ngcourse-next#40]
Refreshing the logged in main page exposes issues (sometimes) with content not being rendered because the Store subscription callbacks (in the TaskListComponent for example) do not trigger a digest after changing the store state. 

Is that issue not present whenever we're making changes from an Observable subscription? What should be responsible for triggering a digest in these cases, and when should it be done?

FYI @igor-ka 

![screen shot 2015-11-11 at 11 34 54 am](https://cloud.githubusercontent.com/assets/898763/11096475/49c85016-8868-11e5-999a-eea383f7841b.png)

**Comment by igor-ka** [comment]
@steven-ks this is an rxjs bug, make sure you use version 4.0.0 not anything higher...
delete node_modules folder after you change that as well.

Also, about Flux, look at the structure in my fork for now, I'll do a PR to get it in the main branch when i get a chance, this is how i teach it in class (as in my fork)

**Comment by steven-ks** [comment]
Ok that's good to know, and yes, making sure I have only 4.0.0 got things working as expected. Can you highlight how this works? I can't (easily) find any evidence as to how those scope digests are being triggered.

Regarding flux, I will follow that branch of yours (`fix-flux`). So actions are taking on responsibility for making API requests (getting fatter)? I have a handful of conceptual questions about flux, but I want to wait until you are in the office to go over them.

Thanks.
